version: "3.9"
services:
  ctf:
    container_name: ctf
    hostname: ctf
    build:
      context: .
      dockerfile: CTFDockerfile
    ports:
      - "80:5050"
    volumes:
      - ./src/data:/app/data